#!/bin/sh
must(){
until "$@"
do
echo
done
}
sed -i "s|http://archive.ubuntu.com|http://mirrors.ustc.edu.cn|g" /etc/apt/sources.list
sed -i "s|http://ports.ubuntu.com|http://mirrors.ustc.edu.cn|g" /etc/apt/sources.list
must apt update
must apt full-upgrade -y
must apt install locales language-selector-common tightvncserver nano lxde-core language-pack-zh-* -y
xs=""
for x in $(check-language-support)
do
xs="$xs $(echo $x|grep ^font)"
done
must apt install $xs -y
tightvncserver :0
tightvncserver -kill :0
echo 'startlxde' >> $HOME/.vnc/xstartup
echo '#!/bin/sh
exec tightvncserver -geometry 825x1200 :0' > $HOME/x
chmod +x $HOME/x
